// export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_START_PAGE = 'CHANGE_START_PAGE';
export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST';
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS';
export const FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE';