export const CHANGE_START_PAGE = 'CHANGE_START_PAGE';
export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST';
export const SAVE_RESULT = 'SAVE_RESULT';
export const FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE';
export const APP_LOADED = 'APP_LOADED';
export const INCREMENT_FETCHED_PAGES = 'INCREMENT_FETCHED_PAGES';

//API

export const GET_MARKS = 'GET_MARKS';