export const CHANGE_START_PAGE = 'CHANGE_START_PAGE';
export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST';
export const SAVE_RESULT = 'SAVE_RESULT';
export const FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE';
export const PAGES_LOADED = 'PAGES_LOADED';
export const SAVE_AVERAGES = 'SAVE_AVERAGES';

//API

export const SAVE_MARKS = 'SAVE_MARKS';